### ISSUE TITLE
Add github ribbon to elgg.org

### ISSUE THREAD

**Issue by Srokap** [Elgg/elgg_org_theme#1]
How about adding "fork me on github" ribbon on elgg.org? Would be nice and might actually attract some developers that see it. I know that when I see it on project's page it often attracts me to review project in more detail.

See: https://github.com/blog/273-github-ribbons

**Comment by brettp** [comment]
Not sure how I feel about this. I've always thought those things were a bit tacky. I'm leaning more toward making a developer's or contributing section more obvious. Other thoughts?

**Comment by ewinslow** [comment]
Interesting. I liked the idea -- even considered adding it to plugins that specify a github repo.

**Comment by brettp** [comment]
I'll add it and get some feedback. I'm close to having the redesign completed and am planning to put it on a test server for feedback.

**Comment by ewinslow** [comment]
Saw your work recently. Really looking forward to this.

**Comment by beck24** [comment]
I agree with @Srokap - when I see the 'fork me on github' banner I tend to spend more time looking at a project.  I don't mind the look of it either.

Just my 2 cents :)
